// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlucmlnjoausnbnexvts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdWNtbG5qb2F1c25ibmV4dnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTkzMjEsImV4cCI6MjA2ODM5NTMyMX0.d4PpVMbtlgyAcXDAwI7casCGgCNUI4z5wyDilRhMDU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});